approve_by_comment: true
approve_regex: '^(Approved|:\+1:)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: true
author_approval: required
reviewers:
    -
        name: admin
        required: 1
        members:
            - KaivoAnastetiks

